-- AlterTable
ALTER TABLE `CustomerSession` ADD COLUMN `stockReview` JSON NULL;

-- AlterTable
ALTER TABLE `SessionEvent` MODIFY `eventType` ENUM('SESSION_CREATED', 'DEMO_STARTED', 'DEMO_ENDED', 'DECISION_MADE', 'PRODUCT_SELECTION_STARTED', 'PRODUCT_SELECTION_CONFIRMED', 'STOCK_SEARCHING', 'STOCK_FOUND', 'STOCK_SENT_TO_CASHIER', 'STOCK_OUT_OF_STOCK', 'CUSTOMER_CANCELLED', 'STOCK_REPORTED_MISSING', 'STAFF_RESOLVED_STOCK_REVIEW', 'CASHIER_RECEIVED', 'CASHIER_SCANNED', 'BILL_OPENED', 'COMPLETED') NOT NULL;
